color0 #121316
color1 #ffb4ab
color2 #a6c8ff
color3 #bdc7dc
color4 #dbbde2
color5 #a6c8ff
color6 #bdc7dc
color7 #e3e2e6
color8 #8d9199
color9 #ffb4ab
color10 #a6c8ff
color11 #bdc7dc
color12 #dbbde2
color13 #a6c8ff
color14 #bdc7dc
color15 #e3e2e6

cursor                #e3e2e6
cursor_text_color     #121316
background            #121316
foreground            #e3e2e6
selection_foreground  #c4c6cf
selection_background  #43474e
active_border_color   #a6c8ff
inactive_border_color #43474e
url_color             #a6c8ff

active_tab_foreground   #003060
active_tab_background   #a6c8ff
inactive_tab_foreground #c4c6cf
inactive_tab_background #43474e
cursor_trail_color      #c4c6cf
