color0 #121316
color1 #ffb4ab
color2 #a5c8ff
color3 #bcc7dc
color4 #dabde2
color5 #a5c8ff
color6 #bcc7dc
color7 #e3e2e6
color8 #8d9199
color9 #ffb4ab
color10 #a5c8ff
color11 #bcc7dc
color12 #dabde2
color13 #a5c8ff
color14 #bcc7dc
color15 #e3e2e6

cursor                #e3e2e6
cursor_text_color     #121316
background            #121316
foreground            #e3e2e6
selection_foreground  #c3c6cf
selection_background  #43474e
active_border_color   #a5c8ff
inactive_border_color #43474e
url_color             #a5c8ff

active_tab_foreground   #00315e
active_tab_background   #a5c8ff
inactive_tab_foreground #c3c6cf
inactive_tab_background #43474e
cursor_trail_color      #c3c6cf

background_opacity 0.9
